# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

def setup(app):
    app.add_config_value('privado', False, 'env')
   
privado = True

# La opcion por defecto falla en el Kindle.
#smartquotes = False


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'Apuntes'
copyright = '2020, Jorge P'
author = 'Jorge P'

from datetime import datetime
today = datetime.today().strftime('%Y.%m.%d')

if privado:
  # The short X.Y version
    version = today + '-priv'
else:   
    version = today + '-pub'

# The full version, including alpha/beta/rc tags
release = version


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.imgconverter',
    'sphinx.ext.graphviz',
    'sphinx.ext.imgmath',
    'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'es'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

pygments_style = None
nitpicky = True
numfig = True


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_rtd_theme'

#html_theme_path = ["_themes", ]
html_style = 'css/my_theme.css'

html_theme_options = {
    'prev_next_buttons_location': None,
    'style_external_links': True,
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': False,
    'navigation_depth': -1,
    'includehidden': False,
    'titles_only': True,
}

html_show_sourcelink = False
html_show_sphinx = False
html_show_copyright = False


# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# LaTeX

#latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',

    #'papersize': 'a4paper',
    #'preamble': r'''
        #\setcounter{tocdepth}{3}
        #\usepackage{charter}
        #\usepackage[defaultsans]{lato}
        #\usepackage{inconsolata}   
    #''',
    #'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
    #'sphinxsetup': 'verbatimwithframe=false, VerbatimColor={rgb}{0.97,0.97,0.97}',
    #'sphinxsetup': 'hmargin={0.5in}, vmargin={1in}, marginpar=0in'

#}


# PANTALLA MOVIL. LETRA GRANDE SIN MARGENES.
latex_elements_movil = {
    'papersize': 'a4paper',
    'pointsize': '12pt',
    'preamble': r'''
        \setcounter{tocdepth}{3}
        \usepackage{charter}
        \usepackage[defaultsans]{lato}
        \usepackage{inconsolata}   
    ''',
    'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
    'sphinxsetup': 'hmargin={0.2in}, vmargin={0.7in}, marginpar=0in, shadowsize=0pt, VerbatimBorderColor={rgb}{0.9,0.9,0.9}'
}


# PANTALLA ORDENADOR E IPAD. LETRA GRANDE CON MARGENES PEQUENYOS.
latex_elements_ordenador = {
    'papersize': 'a4paper',
    'pointsize': '12pt',
    'preamble': r'''
        \setcounter{tocdepth}{3}
        \usepackage{charter}
        \usepackage[default]{lato}
        \usepackage{inconsolata}   
    ''',
    'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
    'sphinxsetup': 'hmargin={0.5in}, vmargin={1.0in}, marginpar=0in, shadowsize=0pt, VerbatimBorderColor={rgb}{0.9,0.9,0.9}'
}


# IMPRESION. LETRA PEQUENYA CON MARGENES NORMALES Y ASIMETRICOS.
latex_elements_impresion = {
#latex_elements = {
    'papersize': 'a4paper',
    'preamble': r'''
        \setcounter{tocdepth}{3}
        \usepackage{charter}
        \usepackage[defaultsans]{lato}
        \usepackage{inconsolata}   
    ''',
    'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
    'sphinxsetup': 'hmargin={0.8in,0.5in}, vmargin={1in}, marginpar=0in, shadowsize=0pt, VerbatimBorderColor={rgb}{0.9,0.9,0.9}'
}

latex_elements = latex_elements_ordenador

#latex_documents = [
    #(master_doc, 'apuntes.tex', u'apuntes',
     #u'Jorge P', 'manual'),
#]

latex_use_parts = True
latex_show_pagerefs = True
latex_show_urls = 'footnote'


# -- Extension configuration -------------------------------------------------

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True
